// Email leads organized by category for targeted outreach
// Each lead has name, email, business info, and which sequence to use

export type Lead = {
  name: string;
  email: string;
  businessName: string;
  category: "law-firm" | "dentist" | "plumber" | "saas" | "other";
  city?: string;
  state?: string;
  website?: string;
  sequence: "local-business-seo" | "indie-hacker-partnership";
  priority: "high" | "medium" | "low";
  // === 发送跟踪（默认 0） ===
  sentCount: number;       // 已发了几封（0-5）
  lastSentAt?: string;     // 最后发送日期：YYYY-MM-DD
  nextStep?: string;       // 下一步动作提醒
};

// Cleaned and deduplicated leads from the CSV data
export const leads: Lead[] = [
  // === HIGH PRIORITY: Already engaged or hot leads ===
  {
    name: "Keegan Fonte",
    email: "keegan@saasdummies.com",
    businessName: "SaaS Dummies",
    category: "saas",
    website: "https://saasdummies.com",
    sequence: "indie-hacker-partnership",
    priority: "high",
    sentCount: 1, lastSentAt: "2026-07-14",
  },
  {
    name: "Khashayar",
    email: "k.mansourizadeh@starnustech.com",
    businessName: "Starnus",
    category: "saas",
    website: "https://starnustech.com",
    sequence: "indie-hacker-partnership",
    priority: "high",
    sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === LAW FIRMS ===
  { name: "", email: "info@lemonlaw.com", businessName: "Lemon Law Experts", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@nolemon.com", businessName: "No Lemon Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@unitedlaw.com", businessName: "United Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@pacificattorneygroup.com", businessName: "Pacific Attorney Group", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Chris", email: "chris@thecbslaw.com", businessName: "CBS Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@knightlaw.com", businessName: "Knight Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Eben", email: "eben@eyebytes.com", businessName: "US Attorney", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "managements@theattorneygroup.com", businessName: "The Attorney Group", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "customercare@theattorneygroup.com", businessName: "The Attorney Group", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@ariellawgroup.com", businessName: "Ariel Law Group", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "whiteglove@topdoglaw.com", businessName: "Top Dog Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "intake@topdoglaw.com", businessName: "Top Dog Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "familylawattorneyla@gmail.com", businessName: "Family Law Attorney", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@mylawcompany.com", businessName: "My Law Company", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Nick", email: "nick@mylawcompany.com", businessName: "My Law Company", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@theleelegal.net", businessName: "Lee Legal Group", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === LAW FIRMS: Los Angeles (new from search) ===
  { name: "Arash", email: "akvozlegal@gmail.com", businessName: "Arash Law", category: "law-firm", city: "Los Angeles", website: "https://localinjurylawyers.org", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Michael", email: "michaelkarns52@gmail.com", businessName: "Karns & Karns", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@dklaw.com", businessName: "DK Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@WalchLaw.com", businessName: "Walch Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Howard", email: "howardkornberglawfirm@gmail.com", businessName: "Howard Craig Kornberg Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Edwin", email: "edwin@hstonelaw.com", businessName: "Hillstone Law", category: "law-firm", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === DENTISTS ===
  { name: "", email: "info@centredent.com", businessName: "Centre Dent", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@pearldentalnyc.com", businessName: "Pearl Dental NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@villagedentalnyc.com", businessName: "Village Dental NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@rockcenterdental.com", businessName: "Rock Center Dental", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "manager@tribecadentalny.com", businessName: "Tribeca Dental", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@skydentalnyc.com", businessName: "Sky Dental NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@dentistonmadison.com", businessName: "Dentist on Madison", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "sounddentalnyc@gmail.com", businessName: "Sound Dental NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@nycdentalimplantscenter.com", businessName: "NYC Dental Implants", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "care@makingyousmile.nyc", businessName: "Making You Smile NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "patientcare@212dentalcare.com", businessName: "212 Dental Care", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@80walldental.com", businessName: "Fidi Dental NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "nycmidtown@outlook.com", businessName: "NY Midtown Dental", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === PLUMBERS: Chicago (原有) ===
  { name: "", email: "info@firstchicagoplumbing.com", businessName: "First Chicago Plumbing", category: "plumber", city: "Chicago", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "unitedsewer5@gmail.com", businessName: "Sewer United", category: "plumber", city: "Chicago", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@plumbingdept.com", businessName: "Plumbing Dept", category: "plumber", city: "Chicago", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === PLUMBERS: Los Angeles (已验证有效 85个) ===
  { name: "", email: "info@pacificplumbingteam.com", businessName: "Pacific Plumbing Team", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@socalemergencyplumbinglosangeles.com", businessName: "SoCal Emergency Plumbing LA", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@247rooterservice.com", businessName: "24/7 Rooter Service", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@themagicrooter.com", businessName: "Magic Rooter & Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@americanaplumbing.com", businessName: "Americana Plumbing Experts", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@johnsplumber.com", businessName: "John's Plumbing & Drain Services", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@gr-plumbing.com", businessName: "GR Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@monkeywrenchservices.com", businessName: "Monkey Wrench Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@makeitrightsvc.com", businessName: "Make It Right Services", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@newproplumbing.com", businessName: "New Pro Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@coasttocoastplumbing.com", businessName: "Coast to Coast Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@valenciasplumbing20.net", businessName: "Valencia's Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@servicechampions.com", businessName: "Service Champions Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@josephandsonsplumbing.com", businessName: "Joseph & Sons Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@calirooters.com", businessName: "Cali Rooter & Plumbing Inc", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@laplumbingcompany.com", businessName: "Los Angeles Plumbing Company", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@conoverplumbing.com", businessName: "Conover Plumbing & Mechanical", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@duoflorooter.com", businessName: "DuoFlo Rooter and Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@elboplumbing.com", businessName: "ELBO PLUMBING", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@speedrootersewers.com", businessName: "Speed Rooter", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@infinityplumbinginc.com", businessName: "Infinity Plumbing Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@laplumbingandbackflow.com", businessName: "LA Plumbing & Backflow", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@realplumbersinc.com", businessName: "Real Plumbers Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@localplumbersla.com", businessName: "Local Plumbers Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@randrplumbingservices.com", businessName: "R&R Plumbing Services", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@capplumbinginc.com", businessName: "CAP Plumbing Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@ciscosplumbingservice.com", businessName: "Cisco's Plumbing Inc", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@plumbingemergencylosangeles.com", businessName: "Richards Rooter and Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@thelosangelesplumbingcompany.com", businessName: "Los Angeles Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@universalplumbers.com", businessName: "Universal Plumbers", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@jvplumbingrooter.com", businessName: "JV Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@happyflushinplumbing.com", businessName: "Happy Flushin Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@randallplumbingpro.com", businessName: "Randall Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@emergency-plumbingservices.com", businessName: "Larchmont Emergency Plumber", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@lincolnpipeplumbing.com", businessName: "Black Cat Plumbing Co", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@plumbingperfectionandrooter.com", businessName: "Plumbing Perfection", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@rooterex.com", businessName: "Rooter Ex Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@allseasonrooterandplumbing.com", businessName: "All Season Rooter & Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@nonstoplumbing.com", businessName: "Non Stop Plumbing & Rooter", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@fixitquickplumbinginc.com", businessName: "Fix It Quick Plumbing Inc", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@oandoplumbing.com", businessName: "O & O Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@pershingplumbing.com", businessName: "Pershing Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@legacyrooterandplumbing.com", businessName: "Legacy Rooter & Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@oneproplumbing.net", businessName: "One Pro Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@jvsplumbingnrooter@gmail.com", businessName: "JV's Plumbing & Rooter", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@elizepedaplumbinginc@gmail.com", businessName: "Eli Zepeda Plumbing", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@californiadrainsinc@gmail.com", businessName: "California Drains Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@tonysplumbingpro.com", businessName: "Tony's Plumbing Inc.", category: "plumber", city: "Los Angeles", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === OTHERS (general small business) ===
  { name: "", email: "info@luxerxnyc.com", businessName: "Luxe RX NYC", category: "other", city: "New York", sequence: "local-business-seo", priority: "low", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === ELECTRICIANS: Houston (new) ===
  { name: "", email: "lighthouseelectric.texas@gmail.com", businessName: "Lighthouse Electric", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "allornothingunited@gmail.com", businessName: "All Or Nothing United Electrical", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "ggjelectric.owner@gmail.com", businessName: "GGJ Electric", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@harmonyelectric.com", businessName: "Harmony Electric Co", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@aaronselectricalservice.com", businessName: "Aaron's Electrical Service", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "vproelectric@gmail.com", businessName: "VPRO Electric LLC", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "mrchampionelectric@gmail.com", businessName: "MR CHAMPION ELECTRIC LLC", category: "other", city: "Houston", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === ROOFING: Dallas (new) ===
  { name: "", email: "totaltexasroofing@gmail.com", businessName: "Total Texas Roofing", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "ajsroofingfencingcompany@gmail.com", businessName: "AJ's Roofing & Fencing", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "stockyardroofing@gmail.com", businessName: "Stockyard Roofing", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "Info@Firstunitedroofing.com", businessName: "First United Roofing", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@honestroof.com", businessName: "HonestRoof.com", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@appleroof.com", businessName: "Apple Roofing", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@roofinggiant.com", businessName: "Roofing Giant", category: "other", city: "Dallas", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === DENTISTS: New York (new from search) ===
  { name: "", email: "alladvanceddentistry@yahoo.com", businessName: "All Advanced Dentistry", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "esdsoffice@gmail.com", businessName: "Elite Smile NYC", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "janeyang800@yahoo.com", businessName: "Jane Yang Dental", category: "dentist", city: "New York", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === CPA: Austin (new) ===
  { name: "Rebecca", email: "rsterrycpa@gmail.com", businessName: "Rebecca S. Terry CPA", category: "other", city: "Austin", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "ruben@rubenruiz-cpa.com", businessName: "Ruben M. Ruiz CPA", category: "other", city: "Austin", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "rcoyner@coynercpa.com", businessName: "Roger E. Coyner CPA", category: "other", city: "Austin", state: "TX", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === LANDSCAPING: Phoenix (new) ===
  { name: "", email: "sergiovilla1027@gmail.com", businessName: "Complete Landscape Management", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "landscapelaveen@gmail.com", businessName: "Landscape Laveen", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "rafaelsantanalandscaping1979@gmail.com", businessName: "Santana Landscaping", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "motherandsons.landscape98@gmail.com", businessName: "Mother & Sons Landscaping", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "r.storres4@gmail.com", businessName: "Steve's Complete Lawn Service", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "paradizwithjim@gmail.com", businessName: "Jim's Paradise Creations", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@creativegreenaz.com", businessName: "CGL Landscaping", category: "other", city: "Phoenix", state: "AZ", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === REALTORS: Miami (new) ===
  { name: "Jenilyn", email: "jenilyn.m008@gmail.com", businessName: "Jenilyn Martinez - Compass", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Luis", email: "luisreyesrealty@gmail.com", businessName: "Luis Reyes - Realty ONE Group", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Yuleysmi", email: "myrealtoryuly@gmail.com", businessName: "Yuleysmi Socarras - Elite Ocean View Realty", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Anet", email: "anetortiz@gmail.com", businessName: "Anet Ortiz PA - Realtor", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Yenisei", email: "yenipimentelrealtor@gmail.com", businessName: "Yenisei Pimentel - Realty ONE Group", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Andreana", email: "andreanajackson@gmail.com", businessName: "Andreana Jackson - Douglas Elliman", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Victoria", email: "vicktoriakorotaeva@gmail.com", businessName: "Victoria Korotaeva - London Foster Realty", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "Simone", email: "realtorsisi@gmail.com", businessName: "Simone Campos - Avantway", category: "other", city: "Miami", state: "FL", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === CHIROPRACTOR: Denver (new) ===
  { name: "", email: "jenn.ryan731@gmail.com", businessName: "AIM High Chiropractic", category: "other", city: "Denver", state: "CO", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@6thavenuechiro.com", businessName: "6th Avenue Chiropractic & Wellness", category: "other", city: "Denver", state: "CO", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@denver-chiropractic.com", businessName: "Denver Integrated Spine Center", category: "other", city: "Denver", state: "CO", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@levelchiro.com", businessName: "Level Chiropractic", category: "other", city: "Denver", state: "CO", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "chasechiropractic@gmail.com", businessName: "Chase Chiropractic Clinic", category: "other", city: "Denver", state: "CO", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  // === HVAC: Atlanta (new) ===
  { name: "", email: "frittsheatingandair@gmail.com", businessName: "Fritts Heating & Air", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "oneseasoncs@gmail.com", businessName: "One Season Comfort Solutions", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "chambleehvacservice@gmail.com", businessName: "Acme Heating & A/C", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@moncriefair.com", businessName: "Moncrief Heating & Air", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@pvhvac.com", businessName: "PV Heating & Air", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@slusspadgett.com", businessName: "Sluss + Padgett", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
  { name: "", email: "info@centralheat.com", businessName: "Central Heating and Air", category: "other", city: "Atlanta", state: "GA", sequence: "local-business-seo", priority: "medium", sentCount: 1, lastSentAt: "2026-07-14",
  },
];

export function getLeadsBySequence(seq: string): Lead[] {
  return leads.filter(l => l.sequence === seq && l.email.includes("@"));
}

export function getLeadsByPriority(priority: string): Lead[] {
  return leads.filter(l => l.priority === priority && l.email.includes("@"));
}
