export default function Terms() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-20">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: July 6, 2026</p>

      <section className="space-y-6 text-gray-700 leading-relaxed">
        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">1. About SEO Spark</h2>
          <p>
            SEO Spark (seospark.net) is an AI-powered SEO content generation tool. By using our service,
            you agree to these terms.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Free Tier</h2>
          <p>
            We offer 3 free article generations. Usage is tracked via a browser cookie.
            We reserve the right to modify or discontinue the free tier at any time.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Content Ownership</h2>
          <p>
            You own all content you generate using SEO Spark. We claim no ownership or rights
            over your generated articles. You are responsible for reviewing and fact-checking
            all AI-generated content before publishing.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">4. AI Disclaimer</h2>
          <p>
            Content is generated by artificial intelligence and may contain errors, inaccuracies,
            or outdated information. Always verify facts, statistics, and claims before publishing.
            SEO Spark is not responsible for any consequences of publishing unverified AI content.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Acceptable Use</h2>
          <p>
            Do not use SEO Spark to generate spam, misleading content, or content that violates
            applicable laws. We reserve the right to block access for misuse.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Payments</h2>
          <p>
            Paid plans are processed through Paddle. Subscriptions are monthly and
            can be canceled at any time. Refunds are handled as described in our
            <a href="/refund" className="text-blue-600 underline">Refund Policy</a>.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Limitation of Liability</h2>
          <p>
            SEO Spark is provided "as is" without warranties of any kind. We are not liable
            for damages arising from the use or inability to use our service.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Contact</h2>
          <p>
            For questions about these terms, email{' '}
            <a href="mailto:hello@seospark.net" className="text-blue-600 underline">
              hello@seospark.net
            </a>.
          </p>
        </div>
      </section>
    </main>
  );
}
